### PR TITLE
Ignore CSS custom properties in color(<color>)

### LINKED ISSUE #4: Do not throw exception when a color can't be resolved
Ref https://github.com/postcss/postcss/issues/177

### PR DESCRIPTION
**Pull request by drewbourne**
Fixes #4 by skipping any `color` functions that contain a `var`

### CODE REVIEW

**Comment by MoOx** [comment]
I should be something more generic that just send a message using postcss message api, not just related to var. If a resolution fail, we should throw a warning not just throw a fatal.

**Comment by drewbourne** [comment]
Ok, so instead of just skipping `var`, it should attempt to parse & convert the value, and if that fails then log a warning to the postcss result and leave the declaration unmodified?

**Comment by MoOx** [comment]
I guess :)

**Comment by drewbourne** [comment]
Closing this PR in favor of #35 and #36 to address the separate needs for turning errors into postcss warnings, and the need to skip color functions with custom properties.

**Pull request closed without merging**
